# Generated by Django 5.2.9 on 2025-12-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Published_date',
            new_name='published_date',
        ),
    ]
