# Generated by Django 4.2.11 on 2025-10-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_year',
            new_name='publication_year',
        ),
    ]
